---
version: "2.1"
services:
  smokeping:
    image: ghcr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Egypt
    volumes:
      - C:\Users\engmi\smokeping/config:/config
      - C:\Users\engmi\smokeping/data:/data
    ports:
      - 8888:80
    restart: unless-stopped